### ISSUE TITLE
Wind and related issues

### ISSUE THREAD

**Issue by leecemin** [wuespace/telestion-project-daedalus2#4]
**What is needed for the integration of the wind simulation**
- [ ] File upload system 
- [ ] and input at which position what data is available
- [ ] Accesibility to the database for positions or verticlespeed (.txt , .csv or other format)

- [ ] Maybe console to access the matlab-connector

**Comment by cb0s** [comment]
I have multiple questions:

> - [ ] File upload system

Do you want to do this via the front-end? Or do you want to specify a direct path to the simulation via the config? This might be easier to begin with, because for letting the user import the simulation via the frontend we need to communicate with the front end first obviously. This might need time to be implemented.

> - [ ] and input at which position what data is available

Didn't you want to import the data? Isn't the geographic data automatically included in some kind of header?

> - [ ] Accesibility to the database for positions or verticlespeed (.txt , .csv or other format)

What do you mean with that? We have the "standard" mongo db like stated [here](https://github.com/wuespace/telestion-core/pull/61)

> - [ ] Maybe console to access the matlab-connector

This will be a challenge because the whole concept is "input-free" up to this point. I think a solution could be a "remote" client which connects via TCP to the GS and there you can type something in a console which will be executed in a designated verticle.

**Comment by leecemin** [comment]
> What do you mean with that? We have the "standard" mongo db like stated [here](https://github.com/wuespace/telestion-core/pull/61)

this issue is old and at that point the database was not available yet

> Do you want to do this via the front-end? Or do you want to specify a direct path to the simulation via the config? This might be easier to begin with, because for letting the user import the simulation via the frontend we need to communicate with the front end first obviously. This might need time to be implemented.

I think here is the first misunderstanding the file upload system is for the wind-data file only with a fixed path.
It should/has to be at the frontend because it will be needed in Kiruna and the person operating is maybe someone who doesn't really know how everything works. With the frontend it will be less likely to make an error.

> > * [ ]  and input at which position what data is available
> 
> Didn't you want to import the data? Isn't the geographic data automatically included in some kind of header?

That is not what was meant by that. The previous wind-data files I have, they all have the data at different positon for example RE23 had a windspeed at column 5 and the heading at column 6 but RE25&26 had a Wind speed North at column 1 and wind speed East at column 3. maybe you see the problem 

> * [ ]  Maybe console to access the matlab-connector

This was just wishful thinking
